# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraview < Formula
  desc "Revisor semântico para planos Terraform. Combina scanners estáticos
(Checkov, tfsec, Terrascan) com revisão inteligente por IA.
"
  homepage "https://github.com/leonamvasquez/terraview"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.7.0/terraview-darwin-amd64.tar.gz"
      sha256 "3afeeee1b8170b08bcee2d2f8cde35a27cbb8299c22bb856de7d6b6692638377"

      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.7.0/terraview-darwin-arm64.tar.gz"
      sha256 "b390096e251e6b56e4d5bab16fec06aa8f545097a7376d79030a5d899a47ab70"

      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.7.0/terraview-linux-amd64.tar.gz"
      sha256 "b05bd0f2890ddb879f7e8e4af5e5364676b9cbda5d6fb63364a81e123e52ba39"
      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.7.0/terraview-linux-arm64.tar.gz"
      sha256 "368657212418e205a45ce46e5c8968eb338d09e8c68aea4db0f1c8ac918a042d"
      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
  end

  test do
    system bin/"terraview", "version"
  end
end
