# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraview < Formula
  desc "Revisor semântico para planos Terraform. Combina scanners estáticos
(Checkov, tfsec, Terrascan) com revisão inteligente por IA.
"
  homepage "https://github.com/leonamvasquez/terraview"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.6.0/terraview-darwin-amd64.tar.gz"
      sha256 "c5721e2f9cf52b7b5cd629f2631b6a190b2ee8c96a95247d6553147eb5619020"

      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.6.0/terraview-darwin-arm64.tar.gz"
      sha256 "fe346d2e95114fe9c881ee6f9609aadbd3adbc3894a3fb6b564e705f18ed6293"

      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.6.0/terraview-linux-amd64.tar.gz"
      sha256 "7974810f59da8b984a29785ed10a639355f9a5b3b94b9067c000864124a741a1"
      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.6.0/terraview-linux-arm64.tar.gz"
      sha256 "eeed58bae8052717116bbf592d58c69ab1c3d99998e184757185a8d0541c70b6"
      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
  end

  test do
    system bin/"terraview", "version"
  end
end
