# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraview < Formula
  desc "Revisor semântico para planos Terraform. Combina scanners estáticos
(Checkov, tfsec, Terrascan) com revisão inteligente por IA.
"
  homepage "https://github.com/leonamvasquez/terraview"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.9.0/terraview-darwin-amd64.tar.gz"
      sha256 "b81321159917132ecc2893975a91b9f2d7d0669e45694c6630ae60f4a643842b"

      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.9.0/terraview-darwin-arm64.tar.gz"
      sha256 "c908c0fe9ef6ff4da2e8febe2458c6fab751583ad89e46f615295b64a81a0146"

      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.9.0/terraview-linux-amd64.tar.gz"
      sha256 "e13851c0d2b640c3518de23f440ac72f2f0a15cc35d001e0f1268acea276b2af"
      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonamvasquez/terraview/releases/download/v0.9.0/terraview-linux-arm64.tar.gz"
      sha256 "a698475057462c3e4d17dc8a04ab1762c3666bb4792f73400ed1676cc396aa10"
      define_method(:install) do
        bin.install "terraview"
        bin.install_symlink "terraview" => "tv"
        generate_completions_from_executable(bin/"terraview", "completion")
      end
    end
  end

  test do
    system bin/"terraview", "version"
  end
end
